version: "3.9"

services:
  redis:
    image: redis:latest
    command: redis-server --save "" --appendonly no
    ports:
      - 6379:6379
    restart: always

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=passw0rd
      - DOCKER_INFLUXDB_INIT_ORG=soulmachine
      - DOCKER_INFLUXDB_INIT_BUCKET=coinsignal
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-t0ken
    volumes:
      - "influxdb2_data:/var/lib/influxdb2"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=passw0rd
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./configs/grafana/provisioning:/etc/grafana/provisioning:ro"
    depends_on:
      - influxdb
    restart: always

  crawlers:
    build:
      context: ./
      dockerfile: Dockerfile
    image: coinsignal:crawlers
    environment:
      - REDIS_URL=redis:6379
      - FULL_NODE_URL=wss://mainnet.infura.io/ws/v3/6866aa0c8c3d48638fedf2d83c85f4b8
      - CMC_API_KEY=1fb6c6ba-e6de-430b-81ec-ac8909b03a07
      - ETHERSCAN_API_KEY=HHS8I3EHGDS8NIUJERJ9CW5E3BEC8K34E9
    depends_on:
      - redis
    restart: always

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
