version: "3.9"

services:
  redis:
    image: redis:latest
    command: redis-server --save "" --appendonly no
    ports:
      - 6379:6379
    restart: always

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=passw0rd
      - DOCKER_INFLUXDB_INIT_ORG=soulmachine
      - DOCKER_INFLUXDB_INIT_BUCKET=coinsignal
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-t0ken
    volumes:
      - "influxdb2_data:/var/lib/influxdb2"
    restart: always

  coinsignal-frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    image: soulmachine/coinsignal:frontend
    ports:
      - 3000:3000
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-t0ken
      - INFLUXDB_ORG=soulmachine
      - INFLUXDB_BUCKET=coinsignal
      # for development
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=passw0rd
      # for production
      # - GF_SERVER_DOMAIN=coinsignal.org
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_BASIC_ENABLED=false
      # - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - "grafana_data:/var/lib/grafana"
    depends_on:
      - coinsignal-backend
    restart: always

  carbonbot-trade:
    image: soulmachine/carbonbot:latest
    command: ["pm2-runtime", "start", "pm2.trade.config.js"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DATA_DIR # unset
    depends_on:
      - redis
    restart: always

  carbonbot-misc:
    image: soulmachine/carbonbot:misc
    environment:
      - FULL_NODE_URL # wss://mainnet.infura.io/ws/v3/YOUR-PROJECT-ID
      - CMC_API_KEY
      - ETHERSCAN_API_KEY
      - REDIS_URL=redis://redis:6379
      - DATA_DIR # unset
    depends_on:
      - redis
    restart: always

  coinsignal-backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: soulmachine/coinsignal:backend
    environment:
      - REDIS_URL=redis://redis:6379
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-t0ken
      - INFLUXDB_ORG=soulmachine
      - INFLUXDB_BUCKET=coinsignal
    depends_on:
      - carbonbot-trade
      - carbonbot-misc
      - influxdb
      - redis
    restart: always

volumes:
  influxdb2_data:
    driver: local
  grafana_data:
    driver: local
