version: "3.9"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=passw0rd
      - DOCKER_INFLUXDB_INIT_ORG=soulmachine
      - DOCKER_INFLUXDB_INIT_BUCKET=coinsignal
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-t0ken
    volumes:
      - "influxdb2_data:/var/lib/influxdb2"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=passw0rd
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./configs/grafana/provisioning:/etc/grafana/provisioning:ro"
    depends_on:
      - influxdb
    restart: always

  crawlers:
    build:
      context: ./
      dockerfile: Dockerfile
    image: soulmachine/coinsignal:crawlers
    ports:
      - 6379:6379
    environment:
      - FULL_NODE_URL # wss://mainnet.infura.io/ws/v3/YOUR-PROJECT-ID
      - CMC_API_KEY
      - ETHERSCAN_API_KEY
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-t0ken
      - INFLUXDB_ORG=soulmachine
      - INFLUXDB_BUCKET=coinsignal
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb2_data:
    driver: local
  grafana_data:
    driver: local
