[package]
name = "utils"
version = "0.1.1"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-msg-parser = "1.6.2"
log = "0.4"
redis = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
