apiVersion: 1
datasources:
  # - name: InfluxDB
  #   type: influxdb
  #   access: proxy
  #   url: http://influxdb:8086
  #   database: coinsignal
  #   user: admin
  #   password: passw0rd
  #   isDefault: true
  #   editable: false
  #   jsonData:
  #     httpMode: POST
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: my-t0ken
    jsonData:
      version: Flux
      organization: soulmachine
      defaultBucket: coinsignal
      tlsSkipVerify: true
