apiVersion: 1
datasources:
  # - name: InfluxDB
  #   type: influxdb
  #   access: proxy
  #   url: http://influxdb:8086
  #   database: coinsignal
  #   user: admin
  #   password: passw0rd
  #   isDefault: true
  #   editable: false
  #   jsonData:
  #     httpMode: POST
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: INFLUXDB_URL
    isDefault: true
    editable: false
    secureJsonData:
      token: INFLUXDB_TOKEN
    jsonData:
      version: Flux
      organization: INFLUXDB_ORG
      defaultBucket: INFLUXDB_BUCKET
      tlsSkipVerify: true
