{
 "title": "Binance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Funding Rate per Pair",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"funding_rate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"funding_rate\")\n  |> filter(fn: (r) => r[\"exchange\"] == \"binance\")\n  |> filter(fn: (r) => r[\"market_type\"] == \"linear_swap\" or r[\"market_type\"] == \"inverse_swap\")\n  |> group(columns: [\"_measurement\", \"_field\", \"market_type\", \"symbol\"])\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Funding Rate per Coin",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"funding_rate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"funding_rate\")\n  |> filter(fn: (r) => r[\"exchange\"] == \"binance\")\n  |> filter(fn: (r) => r[\"market_type\"] == \"linear_swap\" or r[\"market_type\"] == \"inverse_swap\")\n  |> group(columns: [\"_measurement\", \"_field\", \"base\"])\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trading Volume per Coin",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"candlestick_ext\")\n  |> filter(fn: (r) => r[\"bar_size\"] == \"300000\")\n  |> filter(fn: (r) => r[\"base\"] != \"BTC\")\n  |> filter(fn: (r) => r[\"exchange\"] != \"binance\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_usd\")\n  |> group(columns: [\"_measurement\", \"_field\", \"base\"])\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}