{
 "title": "Funding Rate",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Funding Rate Per Pair",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"funding_rate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"funding_rate\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Funding Rate Per Coin",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"funding_rate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"funding_rate\")\n  |> group(columns: [\"_measurement\", \"_field\", \"exchange\", \"market_type\", \"base\"])\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Funding Rate Per Pair(Every 15 Minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"funding_rate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated_rate\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n  |> yield(name: \"estimated_rate\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Funding Rate Per Coin(Every 15 Minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"funding_rate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated_rate\")\n  |> group(columns: [\"_measurement\", \"_field\", \"exchange\", \"market_type\", \"base\"])\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n  |> yield(name: \"estimated_rate\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}