{
 "title": "Trade",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Buy - Sell (Every 15 minutes)",
   "type": "graph",
   "description": "Every 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"candlestick_ext\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_usd_sell\" or r[\"_field\"] == \"volume_usd_buy\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.volume_usd_buy - r.volume_usd_sell }))\n  |> drop(columns: [\"_start\", \"_stop\", \"volume_usd_sell\", \"volume_usd_buy\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VPIN (Every 15 minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"candlestick_ext\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_usd_sell\" or r[\"_field\"] == \"volume_usd_buy\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.volume_usd_buy - r.volume_usd_sell)/(r.volume_usd_buy + r.volume_usd_sell) }))\n  |> drop(columns: [\"_start\", \"_stop\", \"volume_usd_sell\", \"volume_usd_buy\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trading Volume By Exchange (Every 15 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"candlestick_ext\")\n  |> filter(fn: (r) => r[\"bar_size\"] == \"300000\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_usd\")\n  |> group(columns: [\"_measurement\", \"_field\", \"exchange\"])\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trading Volume By MarketType (Every 15 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"candlestick_ext\")\n  |> filter(fn: (r) => r[\"bar_size\"] == \"300000\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_usd\")\n  |> group(columns: [\"_measurement\", \"_field\", \"market_type\"])\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trading Volume By Coin (Every 15 minutes, Excluding Bitcoin)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"candlestick_ext\")\n  |> filter(fn: (r) => r[\"bar_size\"] == \"300000\")\n  |> filter(fn: (r) => r[\"base\"] != \"BTC\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_usd\")\n  |> group(columns: [\"_measurement\", \"_field\", \"base\"])\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trading Volume By Pair (Every 15 minutes, Excluding Bitcoin)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"coinsignal\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"candlestick_ext\")\n  |> filter(fn: (r) => r[\"bar_size\"] == \"300000\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_usd\")\n  |> group(columns: [\"_measurement\", \"_field\", \"pair\"])\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}